### ISSUE TITLE
[Feature Request] Option to hide the count of pane history 

### ISSUE THREAD

**Issue by nhan000** [pjeby/pane-relief#20]
I'm using this plugin together with your Quick Explorer plugin. When navigating between notes that have and don't have history, there is a jumping motion in the Quick Explorer plugin.

Screenshots:

![image](https://user-images.githubusercontent.com/85216095/178463703-141c26cb-576b-4095-a82e-298fd3ee8bfd.png)

(This was taken using Minimal Theme but it also happens with the default theme).
Not a big issue but quite distracting. I think this can be solved either by 
- providing an option to hide the Pane Relief history count (still keep the back and forward button, like with Google Chrome browser).
- provide a padding between the 2 plugins so that when there is a page history count it doesn't push the Quick Explorer to the right.

**Comment by pjeby** [comment]
For the first option, see issue #13.  For the second, I think the way to go would actually be to set the min-width of the page numbers to a space that can accommodate two digits.  I will probably add that in a future release.  I may also consider supporting the Style Settings plugin as a way to configure some of these things rather than manual CSS snippets.

**Comment by pjeby** [comment]
As of 0.2.2, disabling the history count is also available as an option in the Style Settings plugin, if you have that installed.  And in 0.2.3, I've adjusted the padding and alignment of the buttons to prevent QE from jumping around.
