### ISSUE TITLE
It's too tiring to click every time

### ISSUE THREAD

**Issue by chenxin0397** [pjeby/pane-relief#21]
Pane Relief. Toggle focus lock (disable focus in sidebar).
I'd like to be able to set this up so that I don't have to manually click on it every time I open OB.

**Comment by pjeby** [comment]
It should stay the way you set it in a given vault+workspace, even across restarts.  Is it not doing that?  (I just tried in a fresh vault, it worked fine for me.)

**Comment by pjeby** [comment]
Are you still having this problem?

**Comment by chenxin0397** [comment]
Yes, the problem still exists, there are pictures to prove it!
I recorded my operation process:
At first my OB was open, sidebar focusing disabled
But when I close it and open it again, it is: sidebar focusing enabled
After closing it again and then opening it again: sidebar focusing enabled
![202108161359350001001](https://user-images.githubusercontent.com/73974352/181877864-69c32aa3-ec57-4459-91cc-ba4656fcd016.gif)


But I used the method here to start the OB:
https://tfthacker.medium.com/improve-obsidian-startup-time-on-older-devices-with-the-faststart-script-70a6c590309f

Delays the startup time of this plugin, and this method does not affect the functions of other plugins.
Such as: Remember cursor position (remember-cursor-position)

**Comment by pjeby** [comment]
Pane Relief stores its settings in the workspace (so that it can have different settings per workspace).  This means it has to be enabled when the workspace loads, in order to retrieve those settings.  If it is disabled when Obsidian starts, you will lose any settings that were saved with that workspace.

This is generally an issue with plugins that save state per-workspace, such as the Workspaces Plus plugin's per-workspace theme settings.  There are not many such plugins at present, but I would expect the number to increase in the future.  If you want this state to be saved, you'll need Pane Relief to load at startup, or else you'll need to save a copy of your workspace before exiting and then load that workspace after starting (which will take longer than just having Pane Relief load at startup, and have the additional benefit of saving your panes' forward/back histories, which are *also* stored in the workspace, but you haven't known about it since you were losing it every time by not having Pane Relief enabled at startup.)

**Comment by chenxin0397** [comment]
i see , thanks

**Comment by chenxin0397** [comment]
Is it possible to add an option switch in the settings to enable/disable sidebar focusing?

**Comment by pjeby** [comment]
No.  That would make it not work per-workspace, and would not fix any of the other issues created by loading Pane Relief after workspace start, as described in my previous comment above.
