### ISSUE TITLE
Navigation for history is unaccessible on Mac OS if fullscreened.

### ISSUE THREAD

**Issue by Knight-Law** [pjeby/pane-relief#25]
On MacOS, if you fullscreen Obsidian, you're unable to access the history feature as the buttons located at the top bar are hidden away.

**Comment by pjeby** [comment]
There are several other ways to access it:

* Keyboard commands (I think they are opt forward/back arrows by default?  Check hotkeys for "Navigate forward" and "Navigate back")
* Mouse buttons (if you have a mouse w/forward and back buttons, these can be used to navigate a specific pane by clicking with those buttons on it
* Pane header buttons using the CPHATB plugin (see https://github.com/pjeby/pane-relief#per-pane-navigation-buttons for details)

Currently the Mac menu items do not work (see #11), but hopefully there will be a fix coming from the Obsidian devs at some point.

**Comment by pjeby** [comment]
Since this issue was opened, Obsidian has overhauled its UI and Pane Relief 0.5.0 is now up-to-date with it.  If I understand the issue correctly, it should now be fixed.  Please let me know if the history is still unavailable in fullscreen on Obsidian 1.2.8 (assuming the "tab title bar" is enabled in Obsidian's "Appearance" settings).  Thanks!

**Comment by pjeby** [comment]
Closing due to lack of response
