### ISSUE TITLE
Swipe navigation for MacOS

### ISSUE THREAD

**Issue by kaedonkers** [pjeby/pane-relief#27]
Pane Relief is very useful but I think integration of the MacOS two-finger swipe for forward and back (like in a web browser) would be a great feature to add.
Here is some prior art (which unfortunately no longer seems to be supported or works): https://github.com/liamcain/obsidian-swipe-navigation

**Comment by pjeby** [comment]
So, if that were working, it *should* work with Pane Relief, as it just triggers the standard forward/back operations that Pane Relief monitors.  But I don't have any iOS devices nor do I develop for mobile at the moment.  I'd suggest working with the author of that plugin since they at least knew enough about the subject to make what they did.

**Comment by huyz** [comment]
I think that should be a feature request on Core.

**Comment by pjeby** [comment]
Closing this since it if it can be done, it can and should be done in Obsidian core.  (Pane Relief now shares the core history mechanism, so should be compatible if they add it.)
