### ISSUE TITLE
in 16.2 when i maximize the stack/unstack indicator goes away

### ISSUE THREAD

**Issue by pcause** [pjeby/pane-relief#31]
In 16.2, when I toggle maximize the stack/unstack indicator goes away.  can you leave it there as otherwise it takes 2 commands to get back to tab mode (toggle maximize and then unstack).  Perhaps a second command that toggles stack mode and maximize together would be good.

**Comment by pjeby** [comment]
The actual issue here is that the maximize function wasn't coded to hide the stacked tab headers.  I've updated Pane Relief 0.3.3 to hide them when maximized, and restore them on unmaxmize.  This should eliminate the need to stack/unstack in maximized mode.  Thanks for reporting this issue, I hadn't discovered it myself yet!
