### ISSUE TITLE
Option to disable per-pane history

### ISSUE THREAD

**Issue by ryansalmond** [pjeby/pane-relief#33]
I hope this isn't blasphemy but I find the keyboard shortcuts provided with this plugin useful, and don't find the per-pane history part useful, personally. Nothing against it! I just find a global history more intuitive, but wouldn't want to be without for example "Close Pane and Switch to Adjacent Pane”.
Cheers!

**Comment by pjeby** [comment]
So, good news and bad news.

Good news: I've already started moving some of the per-pane history code to only run under certain conditions.

Bad news: that's because Obsidian 0.16.3 (alpha) adds per-tab history to the core.

In other words, it's very likely that global history will be disappearing from Obsidian *entirely* in the near future, so even if you uninstall Pane Relief entirely it won't help once 0.16 is the public release, unless you stay on 0.15.9 forever.

**Comment by ryansalmond** [comment]
Thank you!
