### ISSUE TITLE
Blank section of Obsidian screen when I split right my tabs.

### ISSUE THREAD

**Issue by floresben73** [pjeby/pane-relief#54]
When I split right my tabs, it causes a big blank spot on the right side of my Obsidian. The void disappears when I disable Pane Relief, and reappears when I turn it back on so as far as I can tell Pane Relief seems to be the issue. Happened regardless of what theme I used, (though I primarily use Blue Topaz) and the void was present with and without the right sidebar being open.

Example photos:
![Obsidiansidebarblank](https://github.com/pjeby/pane-relief/assets/148321050/6355f77e-29fd-436f-bbe8-ae0c4cf42daf)

![Obsidiansidebarblank_openedsidebar](https://github.com/pjeby/pane-relief/assets/148321050/32481b81-e3b1-4328-bf4a-e3ad806cd92b)

**Comment by floresben73** [comment]
There is no blank spot when I split down the tabs.

**Comment by pjeby** [comment]
You probably have Pane Relief's sliding panes turned on.  Use the "Pane Relief: Toggle Sliding Panes (for current window)" command to turn it off.  When it is on, horizontal splits are of fixed size, but you can have as many as you want because the workspace scrolls sideways.  When it's off, you can only have as many splits as fit in the space, but they can be whatever size you like.

**Comment by floresben73** [comment]
That does appear to have solved it. Closed
