### ISSUE TITLE
[FR] Hide the current group

### ISSUE THREAD

**Issue by wwjCMP** [pjeby/pane-relief#55]
I usually use three groups when I'm creating. But sometimes I wish to display only two, or even just one. Is it possible to add a shortcut key to hide the current group?

**Comment by pjeby** [comment]
I'm not sure what that would do, exactly, since Obsidian doesn't have a feature to hide panes.  You can, however use Pane Relief's "Maximize active tab" command to show only the current tab.  You can still switch between tabs, but the tab bar isn't visible.  Perhaps I can come up with a way to add some visual indicator or to show the tabs, or perhaps a "maximize group" function.

Not sure how else I'd go about "hiding" things, though, since then the question is, how you get them back?  How do you even know something's hidden?

**Comment by wwjCMP** [comment]
Regarding your last question, I think the simplest way is that we don't need to completely hide the group; it can be folded into a column that occupies a small space, similar to stacked tabs. By clicking, it can be expanded again.
